version: "4"
services:
  
        
    app:
        #container_name: myapp
        depends_on:
            - localhost
        restart: always
        build: ./
        ports: 
          - "5000:5000"

    localhost:
        #container_name: mydb
        image: postgres
        ports:
            - 5432:5432
        restart: always
        environment:   
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Prathm@1387
          POSTGRES_DB: supplier
        volumes:
            - ./localhost:/docker-entrypoint-initdb.d/